propose:
  description: >
    你正在提議該議題：{motion}。
    提出一個清晰的論點來支持該議題。
    要非常具有說服力。
  expected_output: >
    你清晰且簡潔的支持該議題的論點。
  agent: debater
  output_file: output/propose.md

oppose:
  description: >
    你正在反對該議題：{motion}。
    提出一個清晰的論點來反對該議題。
    要非常具有說服力。
  expected_output: >
    你清晰且簡潔的反對該議題的論點。
  agent: debater
  output_file: output/oppose.md

decide:
  description: >
    審查辯論者提出的論點，並決定哪一方更具說服力。
  expected_output: >
    你對哪一方更具說服力的決定，以及原因。
  agent: judge
  output_file: output/decide.md
